# Validate this file using http://lint.travis-ci.org/
language: python
sudo: false
python:
  - "2.7"
  - "3.6"
addons:
  apt_packages: swig
before_install: pip install pytest
install:
  - pip install -r requirements.txt
  - python setup.py install

script: py.test
